### ISSUE TITLE
Bots should move vehicles to a safer place after being hit and get out if the vehicles are about to explode

### ISSUE THREAD

**Issue by dattran307** [Joe91/fun-bots#216] opened 2022-03-28 04:50 UTC
### Scope

Vehicle bot behavior

### Enhancement

Bots should be more mobile while on vehicles 

### Use case

Bots should be more aggressive and deadly while in vehicles

### I have checked the following...

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by Firjens** [comment] 2022-03-29 08:42
Duplicate of #200 #101 #172 and various other issues.

**Closed by Firjens** 2022-03-29 08:42 UTC
Labels: enhancement

**Comment by Joe91** [comment] 2022-04-01 09:08
They leave the vehicles when they are low on health (you can modify the propability for that).
But they don't know anything about the environment. For that reason they are not able to take cover at all.
