### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Augustakit** [Joe91/fun-bots#290] opened 2023-03-06 12:03 UTC
### Scope

Core

### What happened?

When I was playing "MP_018 ConquestLarge0 1", I suddenly crashed in the middle of the game.However, the number of bots is only 64, and there is no more settings, and I use a 30hz server.This has never happened before.

### What was expected?

Fix the sudden crash of the game

### How can we reproduce and test it?

Startuplist：
vars.roundStartPlayerCount 1
vars.maxPlayers 64
vars.gameModeCounter 100
vars.playerManDownTime 1
vars.playerRespawnTime 1
vars.autoBalance true
vu.ColorCorrectionEnabled false
vu.SunFlareEnabled false
vu.DisablePreRound true
vu.DesertingAllowed false

### Version of fun-bots and VU?

fun-bots-2.8.0-dev2  VU version 19968

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Firjens** [comment] 2023-03-18 12:24
So do these starup commands cause the crash?

**Comment by Augustakit** [comment] 2023-03-20 11:44
Even after I removed some of the instructions

**Comment by BigShottt** [comment] 2023-04-24 23:44
I've been having the same issue. I cannot get through a single round of Funbots on my own server, alone with bots, without the server crashing at some point in the middle of the round.

**Comment by Joe91** [comment] 2023-04-25 15:39
Can you send me the config you are using? Is there a specific map that crashes very soon? Can you reproduce this without other mods?

**Comment by BigShottt** [comment] 2023-04-25 16:05
Hi…I need to do some more testing an pay closer attention as I am a new user of VU & Funbots. 

I became aware of another user reporting that this crashing might be due to the mapvote mod (which I am using). 

I will play again to see if this crashing is really happening near round end, or not.

 

I will let you know.

Dave

**Comment by BigShottt** [comment] 2023-04-26 00:24
Okay, so it seems to be happening every time I’m near end of round when there’s only 1 ticket remaining for the losing team. Crash, every time.

 

I removed the Mapvote mod and now the Funbots mod is the only thing remaining…so I guess it’s either the bots or VU causing the server crash.

 

I’d have no idea how to test this without the bots as I don’t play PvP. It’s crashed so far on 3 out of 3 maps in a row.

 

Not sure what config to send you, I’m running the fun-bots-master.

**Comment by BigShottt** [comment] 2023-04-26 02:55
I also tested this issue with procon running and found that if I leave procon running when the match is about to end that it seems to guarantee a crash…but when I shut Procon off before match ends then things strat to improve and I don’t always get a crash at match end.

 

Here’s what my last test session was like:

 

*	I’d start and join the server
*	then alt-tab out to start Procon
*	choose my map from the list in procon
*	tell procon to start next round so my chosen map would load
*	close Procon and go back to game and the new map would load
*	play to end of match with bots
*	upon match end, next map starts, so I alt-tab again to desktop and start Procon again
*	choose my next map from the list in procon and tell procon to start next round
*	close procon down and go back to game to play until end again

 

After playing 3 matches I think it was the 3rd match that crashed at the end when tickets get to only 1 left…even though procon was shut down.

 

Hope this helps

 

 

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Okay, so it seems to be happening every time I’m near end of round when there’s only 1 ticket remaining for the losing team. Crash, every time.

 

I removed the Mapvote mod and now the Funbots mod is the only thing remaining…so I guess it’s either the bots or VU causing the server crash.

 

I’d have no idea how to test this without the bots as I don’t play PvP. It’s crashed so far on 3 out of 3 maps in a row.

 

Not sure what config to send you, I’m running the fun-bots-master.

**Comment by Joe91** [comment] 2023-04-26 04:31
I just played 10 rounds without a crash at all, even with procon and mapvote (10 Tickets TDM).
I played with the latest dev-commit of fun-bots.
What version are you using and what gamemode and configs do you use?

**Comment by Digitalinsite** [comment] 2023-04-26 07:29
I'm getting the same crash on my end too. Matches run perfectly but crash at the end when it gets down to the last ticket. I'm in process of removing mods one by one to try to narrow it down but it seemed to start to happen after either the last funbots major update or the last VU update - can't be sure though...

**Comment by Joe91** [comment] 2023-04-26 07:55
What version of fun-bots are you using? And dura this happen on all gamemodes? How many bots do you use?
It would help me a lot in the process to reproduce this issue.

**Comment by BigShottt** [comment] 2023-04-26 13:49
I'm using fun-bots-master v2.71 and so far I've only played all my rounds in the Conquest mode with the default amount of bots which your mod provides (which I think is something like 9 or 10 per team?).

The only thing I've touched as far as the bots are concerned is adjusting most of their skills so they're easier (raising some of the default worsening numbers).

VU exe file properties says it's version 1.0

Mapvote v 1.3

**Nothing too unusual about my Startup:**
vars.serverName "BigShot"
vars.gamePassword "123456"
vars.roundRestartPlayerCount 0
vars.roundStartPlayerCount 0
admin.password "123456"
vu.ColorCorrectionEnabled true
vu.SunFlareEnabled false
vu.DisablePreRound true
mapvote.excludecurrentmap false

**Here's my maplist:**
XP1_004 ConquestAssaultSmall0 1
MP_001 ConquestSmall0 1
MP_003 ConquestSmall0 1
MP_011 ConquestSmall0 1
MP_012 ConquestSmall0 1
MP_Subway ConquestSmall0 1
XP1_001 ConquestAssaultSmall0 1
XP1_002 ConquestAssaultSmall0 1

**Comment by Joe91** [comment] 2023-04-26 18:27
Thanks a lot!
Was finally able to reproduce it with conquest and mapvote. Without mapvote I just played several rounds without any issue (used the 2.8.0-dev2 version).
Would recommend to do this as well. Can't identify why this crashes in this combination at all. Really strange stuff.

**Comment by BigShottt** [comment] 2023-04-27 19:31
Sorry to report that even with using 2.8.0dev2 and NO other mods, the VU server still crashed today upon final ticket remaining at end of the 2nd round. That round ending crash you thought you fixed a few months ago still seems to remain today. It's just not every single round now.

Hope you sort it anyway, one day.

**Comment by Joe91** [comment] 2023-04-29 19:36
Can you check if you see any improvement when using the branch "debug_crashes"?

**Comment by Joe91** [comment] 2023-05-04 19:05
I think I found a workaround at least for the moment.
If you change the following two values in the Registry.lua this improves the sability on the EndOfRound a lot...
`		RAYCAST_INTERVAL_ENEMY_CHECK = 0.05,
		-- How often are the connections for a bot-bot-attack checked.
		BOT_BOT_CHECK_INTERVAL = 0.1,`

**Comment by Joe91** [comment] 2023-05-20 17:31
@FlashHit found the fix for this bug! It's included in the new dev-version:
https://github.com/Joe91/fun-bots/releases/tag/v2.8.0-dev4

**Closed by Joe91** 2023-05-20 17:31 UTC
Labels: bug
