### ISSUE TITLE
The module will crash the VU game side and server side when changing the map

### ISSUE THREAD

**Issue by okewen** [Joe91/fun-bots#230] opened 2022-08-23 14:26 UTC
### Scope

Core

### What happened?

The module will crash the VU game side and server side when changing the map,I only added the fun-bot module and tested it. Loading the module and changing the map will cause the vu to crash. This problem seriously affects the game experience. I hope to repair it as soon as possible

### What was expected?

The game can change the map normally

### How can we reproduce and test it?

I didn't modify the crash caused by changing the map

### Version of fun-bots and VU?

fun-bot release 2.6.0-dev2 and 2.5.3     VU 19002 

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by Firjens** [comment] 2022-08-26 13:40
Duplicate of #227

**Closed by Firjens** 2022-08-26 13:40 UTC
Labels: bug
