### ISSUE TITLE
Bots do not attack other bots or players when bot count is high

### ISSUE THREAD

**Issue by EP1CN3SS2** [Joe91/fun-bots#44] opened 2021-03-06 07:39 UTC
32 v 32 bots on Karkand and other maps, Only about 20% of bots on each team shoot other bots or players. The rest just move around and do not react to enemy players or bots at all.

**Comment by SmartShots** [comment] 2021-03-07 00:21
I can confirm there is an issue with the BOTs attacking one another, even with just 12 v 12 BOTs, a lot of the time they are just walking past each other.

**Comment by Joe91** [comment] 2021-03-07 11:41
Its a matter of computing power on the client.
With only one client there are with 3 agains 3 bots 9 possible connections to check. As One client only checks 1 connection every 0.1 second this takes a long time with more bots. I will double check if everything works correctly. As soon as there are more real players on the server the number of checkable connetions inceases a lot...

**Comment by Joe91** [comment] 2021-03-07 18:57
To your example:
with 32 vs 32 there are 1024 possible connections to check.
With only one player it will take 102,4 seconds for one complete cycle. So it can happen very likely that bots totally miss each other.

**Comment by Bizarrus** [comment] 2021-03-08 19:31
I think, the Problem is the iteration/loop with an misimplementedbehavior.

You would have to implement the whole thing like a kind of collision check, that each bot in its instance makes a near-by check of the position. Did you know what i mean?

I have the same problem with 30-40 bots as zombie opponents. It starts lagging because iteration takes so long and then the bot ends up being out of scope. So the bot can never see if there is an opponent nearby because the checks take too long.

The whole thing is probably never noticed with a small number of bots.

**Comment by EP1CN3SS2** [comment] 2021-03-08 20:31
Good point and also why don't we make it so the bots are treated as players, or at least seen as players to the bot, thus they will attack them as well and not differentiate between players and other bots.

**Comment by Joe91** [comment] 2021-03-08 21:08
Right now we need Raycasts to detect if a bot can see a player or bot. But these are only supported by the clients. As a bot has no client a real player has to do the calculation for the bot.
But maybe we can finde a little better algorithm or improve the speed a little.

**Comment by MajorVictory** [comment] 2021-03-09 00:44
I've made some improvements on the latest smart_nodes branch. I tested with 15 bots on each side and it seems to have resolved the issue. If you can, try out this branch and let us know if it solves this issue.

**Comment by Bizarrus** [comment] 2021-03-09 04:51
I will check these today, when i bring up my windows server. I had crashed/misconfigured it yesterday.

**Comment by Bizarrus** [comment] 2021-03-10 18:31
Major has added an fix. On my side, it was an little ugly implementation of Bots since Joe had startet the development.

The commit ed15ce95fc16dc16b30dbd3067385e889c63c37e will fix the issue.

Have you changed your BotNames? If they contain spaces, there could be problems. Previously, the bots were determined based on the player name, which led to problems. The behavior has now been changed a bit.

**Comment by Joe91** [comment] 2021-03-10 18:40
They don't have spaces in at all. You can look them up in the Shared/Constant folder. Glad this works again for you. :-)

**Comment by MajorVictory** [comment] 2021-03-11 06:00
The issue wasn't spaces, the issue was that the client didn't have the same list of names as the server. so I rewrote the client code to be name-independent entirely.

**Comment by Joe91** [comment] 2021-04-24 03:48
Right now no option to improve this...

**Closed by Joe91** 2021-04-24 03:48 UTC
Labels: bot behavior, enhancement
